version: V1

onehouseClientConfig:
  projectId: c7c2d2c9-e906-4507-a277-352216195cd0
  apiKey:  P7NKPi3Oo5araDLsfsjnLQ==
  apiSecret: uqG67BtBibC6tgi7z6kvEUA33fIPAtcxx2ZUjni+4ws=
  userUuid: 6Q76tMzKQeO0RnFfJe8HyGSLNAd2

fileSystemConfiguration:
  s3Config:
    region: us-west-2

metadataExtractorConfig:
  jobRunMode: ONCE
  parserConfig:
    - lake:
      databases:
        - name:
          basePaths:
            - s3://onehouse-customer-bucket-a6de6eac/test_table/