{{- if not .Values.deployAsJob }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakeView
  labels:
    app: lakeView
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lakeView
  template:
    metadata:
      labels:
        app: lakeView
    spec:
      containers:
        - name: lakeView
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- if .Values.configPath }}
          - "-p"
          - "{{ .Values.configPath }}"
          {{- else if .Values.config }}
          - "-c"
          - {{ toJson .Values.config | quote }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
{{- end }}
