name: build-images

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if image tags is empty
        if: inputs.tags == ''
        run: exit 1
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build images
        run: docker build -t lake-view .
      - name: Tag and push image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        run: |
          for input_tag in ${{ inputs.tags }}; do
            docker tag lake-view:latest ${{ secrets.DOCKER_USERNAME }}/lake-view:$input_tag
            docker push ${{ secrets.DOCKER_USERNAME }}/lake-view:$input_tag
            cosign sign --key env://COSIGN_PRIVATE_KEY ${{ secrets.DOCKER_USERNAME }}/lake-view:$input_tag -y
          
            if [[ $input_tag == release-* ]]; then
              docker tag lake-view:latest ${{ secrets.DOCKER_USERNAME }}/lake-view:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/lake-view:latest
              cosign sign --key env://COSIGN_PRIVATE_KEY ${{ secrets.DOCKER_USERNAME }}/lake-view:latest -y
            fi
          done
