name: build-images

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
    secrets:
      CI_PAT:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if image tags is empty
        if: inputs.tags == ''
        run: exit 1
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_PAT }}
          fetch-depth: 0
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: us-west-2
#          role-to-assume: arn:aws:iam::194159489498:role/GithubActionsInstallHudiForGatewayC-RepositoryRole-182NI133SRXP0
#          role-session-name: HudiInstallSession
#          role-duration-seconds: 1200
#      - name: Set Env
#        run: echo "CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain onehouse --domain-owner 194159489498 --query authorizationToken --output text)" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
#          server-id: codeartifact
#          server-username: AWS
#          server-password: CODEARTIFACT_AUTH_TOKEN
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: Build images
        run: docker build -t hudi-metadata-extractor .
      - name: Tag and push image
        run: |
          for input_tag in ${{ inputs.tags }}; do
            docker tag hudi-metadata-extractor:latest ${{ secrets.DOCKER_USERNAME }}/hudi-metadata-extractor:$input_tag
            docker push ${{ secrets.DOCKER_USERNAME }}/hudi-metadata-extractor:$input_tag
          done
