name: metadata-extractor-release

on:
  push:
    branches:
      - 'release-*'

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ github.token }}
          fetch-depth: 0
      - name: Set COMMIT_HASH
        run: echo "COMMIT_HASH=$(git rev-parse $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Set BRANCH_PREFIX
        run: echo "BRANCH_PREFIX=branch/" >> $GITHUB_ENV
      - name: Set RELEASE_BRANCH
        run: echo "RELEASE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Set RELEASE_TAG
        run: echo "RELEASE_TAG=${RELEASE_BRANCH#'$BRANCH_PREFIX'}" >> $GITHUB_ENV
      - id: tags
        run: echo "tags=$RELEASE_TAG" >> $GITHUB_OUTPUT
  build-images:
    needs: generate-tags
    uses: ./.github/workflows/build-images.yaml
    secrets: inherit
    with:
      tags: ${{needs.generate-tags.outputs.tags}}

  build-jars:
    needs: generate-tags
    uses: ./.github/workflows/build-jar.yaml
    secrets: inherit
    with:
      tags: ${{needs.generate-tags.outputs.tags}}